image: node:15.12.0

pages:
  cache:
    paths:
      - node_modules/

  stage: deploy
  script:
    - npm install -g @angular/cli@11.2.6
    - npm install
    - ng build
    - mkdir public
    - mv dist/personal-site/* public/
    - cp public/index.html public/404.html
  artifacts:
    paths:
      - public
  only:
    - main
    - pages
